# Generated by Django 6.0.1 on 2026-04-10 16:39

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.svg', null=True, upload_to=users.models.user_avatar_path),
        ),
    ]
