# Generated by Django 6.0.1 on 2026-04-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='型号')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='厂商')),
                ('car_class', models.CharField(max_length=50, verbose_name='级别')),
                ('energy_type', models.CharField(max_length=20, verbose_name='能源类型')),
                ('motor_power', models.FloatField(blank=True, null=True, verbose_name='电动机总功率(kW)')),
                ('max_horsepower', models.IntegerField(blank=True, null=True, verbose_name='最大马力(Ps)')),
                ('max_speed', models.IntegerField(blank=True, null=True, verbose_name='最高车速(km/h)')),
                ('fuel_tank_volume', models.FloatField(blank=True, null=True, verbose_name='油箱容积(L)')),
                ('curb_weight', models.IntegerField(blank=True, null=True, verbose_name='整备质量(kg)')),
                ('wheelbase', models.IntegerField(blank=True, null=True, verbose_name='轴距(mm)')),
                ('max_torque', models.IntegerField(blank=True, null=True, verbose_name='最大扭矩(N·m)')),
                ('nedc_fuel_consumption', models.FloatField(blank=True, null=True, verbose_name='NEDC综合油耗(L/100km)')),
                ('gear_count', models.IntegerField(blank=True, null=True, verbose_name='挡位数')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='宽(mm)')),
                ('displacement', models.IntegerField(blank=True, null=True, verbose_name='排量(mL)')),
                ('acceleration_time', models.FloatField(blank=True, null=True, verbose_name='官方百公里加速时间(s)')),
                ('electric_range', models.IntegerField(blank=True, null=True, verbose_name='纯电续航里程(km)')),
                ('front_track', models.IntegerField(blank=True, null=True, verbose_name='前轮距(mm)')),
                ('seat_count', models.IntegerField(blank=True, null=True, verbose_name='座位数(个)')),
                ('price', models.FloatField(verbose_name='价格(万元)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '汽车数据',
                'verbose_name_plural': '汽车数据',
                'db_table': 'cars_car',
                'ordering': ['-id'],
            },
        ),
    ]
