# Generated by Django 6.0.1 on 2026-05-04 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('version', models.CharField(max_length=50, verbose_name='模型版本')),
                ('model_type', models.CharField(default='XGBoost', max_length=50, verbose_name='模型类型')),
                ('model_data', models.BinaryField(verbose_name='模型二进制数据')),
                ('feature_names', models.JSONField(default=list, verbose_name='特征名称列表')),
                ('label_encoders', models.BinaryField(blank=True, null=True, verbose_name='标签编码器')),
                ('metrics', models.JSONField(default=dict, verbose_name='模型评估指标')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('description', models.TextField(blank=True, verbose_name='模型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '机器学习模型',
                'verbose_name_plural': '机器学习模型',
                'db_table': 'cars_mlmodel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_features', models.JSONField(verbose_name='输入特征')),
                ('predicted_price', models.FloatField(verbose_name='预测价格(万元)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='预测时间')),
                ('model_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.mlmodel', verbose_name='使用的模型')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '预测历史',
                'verbose_name_plural': '预测历史',
                'db_table': 'cars_prediction_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
