# Generated by Django 6.0.3 on 2026-05-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_favoritecar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='feature_defaults',
            field=models.JSONField(default=dict, verbose_name='特征默认值'),
        ),
    ]
